### ISSUE TITLE
SSL Error some time

### ISSUE THREAD

**Issue by Gopalvenu** [gbowerman/azurerm#11]
Hi ,
We are using azurerm module to get vm list from Azure. But we are getting SSL error some time. After that some getting the vm list. Kindly provide the solution for this.

Error Log : "requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"

Thanks,
Gopal.

**Comment by gbowerman** [comment]
@Gopalvenu after how long do you see the error? you need to refresh the authentication token periodically. For example in the VMSS Editor tool, see function subidkeepalive() in https://github.com/gbowerman/vmssdashboard/blob/master/vmsseditor.py which calls auth() in https://github.com/gbowerman/vmssdashboard/blob/master/subscription.py every 20 minutes.

**Comment by Gopalvenu** [comment]
Hi,
 Thanks for your update. One more clarification, I need to virtual machine active state. How could i get that?

Thanks, 
Gopal.

**Comment by gbowerman** [comment]
Can you clarify what "need to virtual machine active state" means? Do you mean start a VM by using the start_vm() function, or something else?

**Comment by Gopalvenu** [comment]
I need list of vm count with active state and non active state.

**Comment by gbowerman** [comment]
Oh you need a get_vm_instance_view() function, and a list_vm_instance_view(). I'll get right on that.

**Comment by Gopalvenu** [comment]
yes you are correct. If possible help me to that info.

**Comment by gbowerman** [comment]
Added a new function get_vm_instance_view() please give it a try. Next ill work on finding a good list instance view method, and creating an example.

**Comment by gbowerman** [comment]
Added a new function list_vm_instance_view() to list the instance views in a resource group. https://github.com/gbowerman/azurerm/commit/9b5e55df9f4d86d0a6299c7d9913a2985aeb0b04 
@Gopalvenu you should be able to get and list VM instance views now. Thanks for reporting this.

**Comment by Gopalvenu** [comment]
Hi gbowerman,

Thanks. I will try it. May i know which one need to have this version 0.6.15?. And one more big clarification, I need to get vm network banwidth usage. Is this possible via azurerm? Kindly help me.

Thanks,
Gopal.

**Comment by gbowerman** [comment]
For network bandwidth usage can you look here: get_network_usage(access_token, subscription_id, location):
Current version is 0.7.2.

**Comment by Gopalvenu** [comment]
Hi ,

No. I need network(IN and OUT) usage per vm.

Thanks,
Goapl
