### ISSUE TITLE
Customize UserAgent for metrics

### ISSUE THREAD

**Issue by lmazuel** [gbowerman/azurerm#13]
Hi @gbowerman 
Just to confirm what we discussed, could you customize the UserAgent? So the usage of your library can be monitored? Since you receive PRs, people are using it and it's important for the ARM metrics dashboard to identify the source of Python calls.
Thank you,

**Comment by gbowerman** [comment]
Hi @lmazuel thanks for the reminder. Resolved. https://github.com/gbowerman/azurerm/commit/af1888455c52f767f681e114c4fa21e091c01b98
