### ISSUE TITLE
delete_vmss_vms fails on instanceId

### ISSUE THREAD

**Issue by Yanivro** [gbowerman/azurerm#15]
I'm trying to remove a few selected vms from a scale set and if I try to pass a string I get the following error from Azure:
    "message": "Error converting value 16 to type 'System.Collections.Generic.List`1[System.String]'. Path 'instanceIds', line 1, position 19."

If I try to pass an array(Like I do when I run the corresponding PowerShell command(Remove-azurermvmss), I get the following error from the lib:
  File "C:\Python27\lib\site-packages\azurerm\computerp.py", line 183, in delete_vmss_vms
    body = '{"instanceIds" : ' + vm_ids + '}'
TypeError: cannot concatenate 'str' and 'list' objects

It might be expecting a list.
Thanks!

**Comment by Yanivro** [comment]
@gbowerman  Added a pull request to fix this issue:
https://github.com/gbowerman/azurerm/pull/16

**Comment by gbowerman** [comment]
These functions are designed to take a string dump of a Python list object, hence the square brackets. 
I could updated them to take Python list objects directly, but would hesitate to make them take a string that is comma separated list of numbers, as that would be less compatible with a Python list.

**Comment by gbowerman** [comment]
Closing this issue for now. Happy to reopen as needed.
