### ISSUE TITLE
Get Azure VM Metrics data using Insights rest.

### ISSUE THREAD

**Issue by samshinde** [gbowerman/azurerm#3]
@gboweman If you provide to get azure vm metric values data function, then it will be great helpfull to me.

**Comment by gbowerman** [comment]
@samshinde thanks for the request. Is there are particular REST call you'd like to wrap? Or are you referring to pulling data from the storage account where the diagnostic extension dumps performance data?

**Comment by lmazuel** [comment]
Hi @samshinde 
Just for information, ARM VM metrics from Insights team (now called Monitor team) is available is the azure-monitor package:
- https://pypi.python.org/pypi/azure-monitor
- http://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-monitor.html

This is NOT the package from @gbowerman , but I thought it was a valid answer anyway.

My two cents,

**Comment by gbowerman** [comment]
Closing this, as azure Azure monitor functions support was added a while back. See get_metrics_for_resource() for example. 
@samshinde thanks for logging this.
