### ISSUE TITLE
how to use it in Azure China

### ISSUE THREAD

**Issue by pjshi23** [gbowerman/azurerm#9]
i tried to overwrite but failed, any ideas?

azurerm.adalfns.authentication_endpoint='https://login.chinacloudapi.cn/'
azurerm.adalfns.resource='https://management.chinacloudapi.cn/'

**Comment by gbowerman** [comment]
@pjshi23 thanks for logging this issue. I have made the endpoint values optional arguments to the get_access_token() function. If this doesn't work we'll need to investigate the adal library and log an issue there.

**Comment by gbowerman** [comment]
Note until there's a long term fix for this @pjshi23 has created MCazurerm specifically for Azure China. See [https://pypi.python.org/pypi/mcazurerm](https://pypi.python.org/pypi/mcazurerm)

**Comment by gbowerman** [comment]
Resolved in azurerm 0.8.1. https://github.com/gbowerman/azurerm/commit/3703e4d5aa1be95c11e29e7b7727e8da7e8ea914 - set national or government cloud access using three environment variables: AZURE_RM_ENDPOINT, AZURE_AUTH_ENDPOINT, AZURE_RESOURCE_ENDPOINT.
@pjshi23 thanks for raising this issue.
